train: "E:/Dataset/202101_withDinghu/temp/v3_testPreprocessing/train"
valid: "E:/Dataset/202101_withDinghu/temp/v3_testPreprocessing/valid"
test: "/content/drive/MyDrive/pytorchRelated/ResUnet-li/dataset/Ding_v3/test"
save_path: "/content/drive/MyDrive/pytorchRelated/ResUnet-li/dataset/Ding_v3/test_result"
log: "/content/drive/MyDrive/pytorchRelated/ResUnet-li/logs"
logging_step: 39
validation_interval: 180 # Save and valid have same interval
checkpoints: "/content/drive/MyDrive/pytorchRelated/ResUnet-li/checkpoints"
listpath: "/content/drive/MyDrive/pytorchRelated/ResUnet-li/CSV_forLossAcc/"

batch_size: 1 # total 39
lr: 0.01
RESNET_PLUS_PLUS: False
IMAGE_SIZE: 224
CROP_SIZE: 224